### PR TITLE
fix gfortran build issue 

### PR DESCRIPTION
**Pull request by shihyuntang**
@kgullikson88 @gully 
Two changes:

1. change to use the url in issue-15 branch
2. make a gfortran_mode function that will manually add -std=legacy to the makefile.common file for gfortran user with version later than 7.5.0

This should fix all the installation issue we see.

### CODE REVIEW

**Review by gully — COMMENTED** [review]
this re-ordering of `ifort` and `gfortran` makes sense to me.  I attempted to get telfit to work with ifort to no avail.  In principle ifort seems like a more performant option because of its tighter coupling with Intel-specific hardware.  In practice there is some barrier to getting it to couple with telfit that has proven hard to track down.

**Review by gully — APPROVED** [review]

**Comment by gully** [comment]
I'd recommend squashing the commits when accepting the PR.  The other open PR can be rebased on top of this one.

**Comment by shihyuntang** [comment]
Hi @gully ,
Thank you for the approval on the changes.
One question: Is there a schedule on making the updated `telfit` pip installable again after the merge?
It will be nice to know so that I can make the corresponding changes for the`IGRINS RV`.
Thank you.

**Comment by gully** [comment]
After a merge, it should be straightforward to deploy a version to PyPI, though that's under Kevin's credential's I suspect.

**Comment by shihyuntang** [comment]
Hi @kgullikson88 ,

If there is any concern for you from pulling this request please let me know.
Thank you.

**Comment by gully** [comment]
OK, I have merged this PR.  I am inclined to Tag this as a release on GitHub, in preparation for a deploy to PyPI.org

**Pull request merged**
